Repository openshift/special-resource-operator, pull requests merged in 2021-10, with the labels that each got.

#40 Bug 2009888: Rename project to openshift-special-resource-operator
  Makefile.helper.mk
  PROJECT
  bundle/4.9/bundle.Dockerfile
  bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
  bundle/4.9/metadata/annotations.yaml
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
Labels: bugzilla/severity-unspecified, lgtm, approved, bugzilla/valid-bug

#44 Bug 2010931: Remove "Drivers and plugins" category from CSV
  bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#43 Bug 2010911: RenderOperatingSystem() returns wrong OS version on OCP 4.7.24
  pkg/cluster/cluster.go
  pkg/osversion/osversion.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#48 Bug 2009888: SRO package name collision between official and community version
  bundle/art.yaml
  bundle/openshift-special-resource-operator.package.yaml
  bundle/special-resource-operator.package.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#52 Bug 2011977: Use origin image in bundle
  bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
  bundle/image-references
  config/manager/kustomization.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high
