Repository openshift/special-resource-operator, pull requests merged in 2021-11, with the labels that each got.

#63 Bug 2016632: Infoscale-CSI: resizer and provisioner timeouts changed to request timeout values
  charts/deprecated/driver-container-base-0.1.0.tgz
  charts/deprecated/index.yaml
  charts/example/centos-simple-kmod-0.0.1.tgz
  charts/example/connaisseur-0.2.0.tgz
  charts/example/index.yaml
  charts/example/multi-build-0.0.1.tgz
  charts/example/ping-pong-0.0.1.tgz
  charts/example/simple-kmod-0.0.1.tgz
  charts/experimental/cert-manager-1.4.0.tgz
  charts/experimental/index.yaml
  charts/experimental/simple-kmod-0.0.1.tgz
  charts/inaccel/fpga-operator-2.0.1.tgz
  charts/inaccel/index.yaml
  charts/infoscale/index.yaml
  charts/infoscale/infoscale-vtas-0.0.1.tgz
  charts/infoscale/infoscale-vtas-0.0.1/templates/6000-infoscale-csi-driver.yaml
  charts/lustre/index.yaml
  charts/lustre/lustre-aws-fsx-0.0.1.tgz
  charts/olm/cert-manager-0.0.1.tgz
  charts/olm/index.yaml
  charts/staging/index.yaml
  charts/staging/shipwright-4.7.0.tgz
  charts/xilinx/fpga-xrt-driver-4.7.11.tgz
  charts/xilinx/index.yaml
Labels: lgtm, approved

#70 Updated README URL and maintainers
  bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#75 Bug 2022886: Update description URL for operator
  bundle/4.9/manifests/openshift-special-resource-operator.v4.9.0.clusterserviceversion.yaml
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#77 Fixing README to point to the d/s repo.
  README.md
Labels: lgtm, approved

#79 Update OWNERS
  OWNERS
Labels: lgtm, approved, ok-to-test

#68 Add 4.10 bundle and Dockerfile
  Makefile
  bundle/4.10/bundle.Dockerfile
  bundle/4.10/manifests/openshift-special-resource-operator.v4.10.0.clusterserviceversion.yaml
  bundle/4.10/manifests/special-resource-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/4.10/manifests/special-resource-controller-manager-metrics-service_v1_service.yaml
  bundle/4.10/manifests/special-resource-dependencies_v1_configmap.yaml
  bundle/4.10/manifests/special-resource-lifecycle_v1_configmap.yaml
  bundle/4.10/manifests/special-resource-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/4.10/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  bundle/4.10/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/4.10/manifests/sro.openshift.io_specialresources.yaml
  bundle/4.10/metadata/annotations.yaml
  bundle/image-references
  bundle/openshift-special-resource-operator.package.yaml
  config/manager/kustomization.yaml
Labels: lgtm, approved, ok-to-test
