Repository openshift/special-resource-operator, pull requests merged in 2021-09, with the labels that each got.

#33 Bug 2000226: Unable to have multiple charts in one configmap
  .patches/getter.patch.go
  OWNERS
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/special-resource-operator.clusterserviceversion.yaml
  test/e2e/basic/simple-kmod.go
  test/e2e/basic/util.go
  vendor/helm.sh/helm/v3/pkg/getter/getter.patch.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#34 Remove Z from OWNERS
  OWNERS
Labels: lgtm, approved

#38 Bug 2009424: poll.go Deployment availability bug fix and Veritas SpecialResource fixes
  OWNERS
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/2000-infoscale-rest-certificate.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/4000-infoscale-fencing-certificate.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/4100-infoscale-fencing-driver.yaml
  config/rbac/role.yaml
  manifests/0004_clusterrole_special-resource-manager-role.yaml
  manifests/0014_deployment_special-resource-controller-manager.yaml
  pkg/poll/poll.go
  pkg/rbac/rbac.go
  test/e2e/basic/available.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#39 [release-4.9] Bug 2009530: poll.go Deployment availability bug fix and Veritas SpecialResource fixes
  OWNERS
  bundle/4.9/manifests/special-resource-operator.v4.9.0.clusterserviceversion.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/2000-infoscale-rest-certificate.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/3000-driver-container.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/4000-infoscale-fencing-certificate.yaml
  charts/infoscale/infoscale-vtas-0.0.1/templates/4100-infoscale-fencing-driver.yaml
  config/rbac/role.yaml
  manifests/0004_clusterrole_special-resource-manager-role.yaml
  manifests/0014_deployment_special-resource-controller-manager.yaml
  pkg/poll/poll.go
  pkg/rbac/rbac.go
  test/e2e/basic/available.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
