Repository openshift/special-resource-operator, pull requests merged in 2022-06, with the labels that each got.

#215 Bug 2089719: Add arch to kernel versions
  controllers/specialresourcemodule_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#222 Bug 2088324: Some manifests still have KVC references
  bundle/4.11/manifests/openshift-special-resource-operator.v4.11.0.clusterserviceversion.yaml
  charts/example/acm-simple-kmod-0.0.1/acm-simple-kmod.yaml
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
  config/samples/sro_v1beta1_specialresource.yaml
  docs/debug.md
  docs/recipes.md
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#211 Bug 2083514: Add resource removal capabilities
  controllers/specialresource.go
  internal/controllers/finalizers/specialresource.go
  pkg/clients/clients.go
  pkg/clients/mock_clients_api.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high, backport-risk-assessed

#219 Bug 2092572: Add namespace creation to acm-simple-kmod
  charts/example/acm-simple-kmod-0.0.1/templates/0002-policy.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#223 Bug 2093357: hub and spokes: add OCP version retrieval and fix ICE driver
  charts/example/acm-ice-0.0.1/templates/0001-buildconfig.yaml
  charts/example/acm-ice-0.0.1/templates/0002-policy.yaml
  charts/example/acm-ice-0.0.1/templates/0003-placement.yaml
  controllers/specialresourcemodule_controller.go
  pkg/registry/mock_registry_api.go
  pkg/registry/registry.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#224 Bug 2096162: Use official registries for ACM examples
  charts/example/acm-ice-0.0.1/acm-ice.yaml
  charts/example/acm-simple-kmod-0.0.1/acm-simple-kmod.yaml
Labels: bugzilla/severity-unspecified, lgtm, approved, bugzilla/valid-bug

#221 Bug 2093444: Fix filtering for management state
  Makefile
  Makefile.helper.mk
  pkg/filter/filter.go
  test/e2e/basic/available.go
  test/e2e/basic/simple-kmod.go
  test/e2e/basic/util.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#209 Bug 2086432: fix SRO CR finalization in case of an upgrade
  controllers/finalizers.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#227 Bug 2097263: Add removeResource function from 4.11
  controllers/specialresource.go
  pkg/filter/filter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, backport-risk-assessed

#230 Bug 2093357: ACM-ICE: use cluster claims to allow upgrades in spokes
  charts/example/acm-ice-0.0.1/README.md
  charts/example/acm-ice-0.0.1/acm-ice.yaml
  charts/example/acm-ice-0.0.1/templates/0002-policy.yaml
  charts/example/acm-ice-0.0.1/templates/0003-placement.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#232 Bug 2098242: Fix typo in SpecialResourceModule controller log
  controllers/specialresourcemodule_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#231 Bug 2093277: Add ACM resources to resourceVersion update list
  internal/resourcehelper/helper.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#240 Fixing the parameter order in scripts/make-cm-recipe.
  README.md
Labels: lgtm, approved

#235 Bug 2099507: failure to update special-resource-lifecycle table durin…
  bundle/4.10/manifests/special-resource-lifecycle_v1_configmap.yaml
  controllers/specialresource.go
  manifests-k8s/0011_configmap_special-resource-lifecycle.yaml
  manifests/0013_configmap_special-resource-lifecycle.yaml
  pkg/filter/filter.go
  pkg/kernel/kernel.go
  pkg/lifecycle/lifecycle.go
  pkg/poll/poll.go
  pkg/resource/resource.go
  pkg/storage/storage.go
  tools.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#239 Read the openshift-config/user-ca-bundle ConfigMap
  main.go
  pkg/registry/mock_openshift_ca_api.go
  pkg/registry/openshift_ca.go
  pkg/registry/openshift_ca_test.go
  pkg/registry/wrapper.go
  pkg/registry/wrapper_test.go
Labels: lgtm, approved
