Repository openshift/special-resource-operator, pull requests merged in 2022-04, with the labels that each got.

#123 Remove wait from poll package
  controllers/specialresource_controller.go
  pkg/poll/poll.go
  pkg/poll/poll_test.go
Labels: lgtm, approved

#160 Adding CI artifacts.
  ci/podman.yaml
Labels: lgtm, approved

#159 MGMT-9825: create preflight package, responsible for preflight check …
  pkg/helmer/helmer.go
  pkg/helmer/mock_helmer_api.go
  pkg/preflight/mock_preflight_api.go
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
  pkg/runtime/mock_runtime_api.go
  pkg/runtime/runtime.go
Labels: lgtm, approved

#153 Bug 2069612: Special Resource Operator (SRO) - Crash when nodeSelector does not match any nodes
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: bugzilla/severity-unspecified, lgtm, approved, bugzilla/valid-bug

#163 Fixing the default IMG for SRO.
  Makefile
Labels: lgtm, approved

#165 Remove dagrayvid from OWNERS
  OWNERS
Labels: lgtm, approved

#164 Allowing running a specific pkg/spec unit-test.
  Makefile
Labels: lgtm, approved

#167 Adding ownerReference to helm hooks configmaps.
  pkg/helmer/helmer.go
Labels: lgtm, approved

#138 Hub and spokes ACM functionality
  Makefile
  api/v1beta1/specialresource_types.go
  api/v1beta1/zz_generated.deepcopy.go
  charts/example/acm-ice-0.0.1/Chart.yaml
  charts/example/acm-ice-0.0.1/README.md
  charts/example/acm-ice-0.0.1/acm-ice.yaml
  charts/example/acm-ice-0.0.1/templates/0001-buildconfig.yaml
  charts/example/acm-ice-0.0.1/templates/0002-policy.yaml
  charts/example/acm-ice-0.0.1/templates/0003-placement.yaml
  config/crd/bases/sro.openshift.io_specialresourcemodules.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  config/rbac/specialresource_editor_role.yaml
  config/rbac/specialresource_viewer_role.yaml
  controllers/resources.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  controllers/specialresourcemodule_controller.go
  go.mod
  go.sum
  main.go
  manifests/0001_customresourcedefinition_specialresourcemodules.sro.openshift.io.yaml
  manifests/0002_customresourcedefinition_specialresources.sro.openshift.io.yaml
  manifests/0003_serviceaccount_special-resource-controller-manager.yaml
  manifests/0004_role_special-resource-leader-election-role.yaml
  manifests/0005_role_special-resource-prometheus-k8s.yaml
  manifests/0006_clusterrole_special-resource-manager-role.yaml
  manifests/0007_clusterrole_special-resource-metrics-reader.yaml
  manifests/0008_clusterrole_special-resource-proxy-role.yaml
  manifests/0009_rolebinding_special-resource-leader-election-rolebinding.yaml
  manifests/0010_rolebinding_special-resource-prometheus-k8s.yaml
  manifests/0011_clusterrolebinding_special-resource-manager-rolebinding.yaml
  manifests/0012_clusterrolebinding_special-resource-proxy-rolebinding.yaml
  manifests/0013_configmap_special-resource-dependencies.yaml
  manifests/0014_configmap_special-resource-lifecycle.yaml
  manifests/0015_service_special-resource-controller-manager-metrics-service.yaml
  manifests/0016_deployment_special-resource-controller-manager.yaml
  manifests/0017_clusteroperator_special-resource-operator.yaml
  manifests/0018_prometheusrule_special-resource-sro-operator-prometheus-rules.yaml
  manifests/0019_servicemonitor_special-resource-controller-manager-metrics-monitor.yaml
  manifests/0020_specialresource_special-resource-preamble.yaml
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
  pkg/helmer/mock_helmer_api.go
  pkg/resource/mock_resource_api.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/utils/rbac.go
  pkg/watcher/controller_mock_test.go
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
  vendor/github.com/oliveagle/jsonpath/.gitignore
  vendor/github.com/oliveagle/jsonpath/.travis.yml
  vendor/github.com/oliveagle/jsonpath/LICENSE
  vendor/github.com/oliveagle/jsonpath/jsonpath.go
  vendor/github.com/oliveagle/jsonpath/readme.md
  vendor/modules.txt
Labels: lgtm, approved

#168 MGMT-9241: adding preflight controller and reconcilaition loop
  api/v1beta1/preflightvalidation_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/sro.openshift.io_preflightvalidations.yaml
  config/crd/kustomization.yaml
  config/rbac/role.yaml
  controllers/preflightvalidation_controller.go
  controllers/specialresource_controller.go
  internal/controllers/state/mock_statusupdater_api.go
  internal/controllers/state/statusupdater.go
  main.go
  pkg/clients/clients.go
  pkg/clients/mock_clients_api.go
  pkg/preflight/mock_preflight_api.go
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
  pkg/runtime/runtime.go
  pkg/utils/rbac.go
Labels: lgtm, approved

#169 MGMT-10014: preflight should handle multiple daemonsets and buildconf…
  pkg/preflight/preflight.go
  pkg/preflight/preflight_test.go
  skipper.env
Labels: lgtm, approved

#170 Removing debug printouts in the cm-getter plugin
  pkg/helmer/helmer.go
Labels: lgtm, approved

#174 Enhancing returned errors for pkg/kernel.
  pkg/kernel/kernel.go
Labels: lgtm, approved

#134 Bug 2059843: add new metrics, completedKind and used Nodes
  Dockerfile.special-resource-operator-build
  api/v1beta1/zz_generated.deepcopy.go
  pkg/lifecycle/lifecycle.go
  pkg/metrics/metrics.go
  pkg/resource/resource.go
  skipper.env
  skipper.yaml
  vendor/github.com/google/go-containerregistry/pkg/crane/options.patch.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#175 Bug 2079788: Handle concurrent map access
  pkg/watcher/watcher.go
  pkg/watcher/watcher_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent
