Repository openshift/special-resource-operator, pull requests merged in 2022-03, with the labels that each got.

#120 Support for operator Force/Managed/Removed/Unmanaged states
  api/v1beta1/specialresource_types.go
  config/crd/bases/sro.openshift.io_specialresources.yaml
  controllers/specialresource.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: lgtm, approved

#114 Bug 2054787: SRO controller crashes when pull-secret holds bad permissions
  pkg/registry/registry.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#119 Cache DTK last layer info
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: lgtm, approved

#104 Use DTK ImageStream to get an DTK image URL
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/mock_cluster_api.go
  pkg/registry/mock_registry_api.go
  pkg/registry/registry.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: lgtm, approved

#100 Remove NFD runtime dependency
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/kernel/kernel.go
  pkg/kernel/kernel_test.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  pkg/utils/osversion.go
  pkg/utils/osversion_test.go
Labels: lgtm, approved, ok-to-test

#132 MGMT-9551 - extend Regsitry API to allow querring different image layers
  pkg/registry/mock_registry_api.go
  pkg/registry/registry.go
Labels: lgtm, approved

#130 Update bundle for 4.11
  Makefile.helper.mk
  bundle/4.11/bundle.Dockerfile
  bundle/4.11/manifests/image-references
  bundle/4.11/manifests/openshift-special-resource-operator.v4.11.0.clusterserviceversion.yaml
  bundle/4.11/manifests/special-resource-controller-manager-metrics-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  bundle/4.11/manifests/special-resource-controller-manager-metrics-service_v1_service.yaml
  bundle/4.11/manifests/special-resource-dependencies_v1_configmap.yaml
  bundle/4.11/manifests/special-resource-lifecycle_v1_configmap.yaml
  bundle/4.11/manifests/special-resource-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/4.11/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_role.yaml
  bundle/4.11/manifests/special-resource-prometheus-k8s_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/4.11/manifests/special-resource-sro-operator-prometheus-rules_monitoring.coreos.com_v1_prometheusrule.yaml
  bundle/4.11/manifests/sro.openshift.io_specialresources.yaml
  bundle/4.11/metadata/annotations.yaml
  config/manager/kustomization.yaml
  config/manifests/bases/openshift-special-resource-operator.clusterserviceversion.yaml
Labels: lgtm, approved

#131 Rework logs in all packages
  controllers/resources.go
  controllers/scale_up_down.go
  controllers/specialresource.go
  internal/controllers/finalizers/specialresource.go
  main.go
  pkg/assets/assets.go
  pkg/clients/clients.go
  pkg/filter/filter.go
  pkg/helmer/helmer.go
  pkg/registry/registry.go
  pkg/resource/resource.go
  pkg/runtime/runtime.go
  pkg/upgrade/upgrade.go
Labels: lgtm, approved

#135 Fix make bundle-push target
  Makefile
Labels: lgtm, approved

#126 Properly determine kernel affinity in controller
  controllers/resources.go
Labels: lgtm, approved

#133 MGMT-9548: adding API to get DTK info based on DTK image
  pkg/upgrade/mock_upgrade_api.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
Labels: lgtm, approved

#136 Fix module name & imports: remove psap
  api/v1beta1/specialresource_types.go
  cmd/cli/cli_test.go
  cmd/leaderelection/options_test.go
  controllers/resources.go
  controllers/scale_up_down.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  controllers/upgrade.go
  go.mod
  internal/controllers/finalizers/specialresource.go
  internal/controllers/finalizers/specialresource_test.go
  internal/controllers/state/clusteroperator.go
  internal/controllers/state/clusteroperator_test.go
  internal/controllers/state/mock_statusupdater_api.go
  internal/controllers/state/statusupdater.go
  internal/controllers/state/statusupdater_test.go
  internal/resourcehelper/helper_test.go
  main.go
  pkg/assets/assets_test.go
  pkg/clients/clients_test.go
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
  pkg/kernel/kernel.go
  pkg/lifecycle/lifecycle.go
  pkg/lifecycle/lifecycle_test.go
  pkg/poll/poll.go
  pkg/poll/poll_test.go
  pkg/proxy/proxy.go
  pkg/proxy/proxy_test.go
  pkg/registry/registry.go
  pkg/registry/registry_test.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
  pkg/runtime/mock_runtime_api.go
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
  pkg/scheme/scheme_test.go
  pkg/state/state_test.go
  pkg/storage/storage.go
  pkg/storage/storage_test.go
  pkg/upgrade/mock_upgrade_api.go
  pkg/upgrade/upgrade.go
  pkg/upgrade/upgrade_test.go
  test/deploy/deploy.go
  test/e2e/basic/ping-pong_test.go
  test/e2e/basic/simple-kmod_test.go
  test/e2e/basic/specialresource_test.go
  test/e2e/basic/util_test.go
  test/framework/create_from_yaml.go
  test/undeploy/undeploy.go
Labels: lgtm, approved

#115 Change location of Helm's cache
  README.md
  config/manager/manager.yaml
  main.go
  manifests-k8s/0013_deployment_special-resource-controller-manager.yaml
  manifests/0015_deployment_special-resource-controller-manager.yaml
  pkg/helmer/helmer.go
Labels: lgtm, approved

#137 Add conditions to SpecialResource status
  api/v1beta1/specialresource_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/sro.openshift.io_specialresources.yaml
  controllers/resources.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  controllers/upgrade.go
  internal/controllers/state/mock_statusupdater_api.go
  internal/controllers/state/statusupdater.go
  internal/controllers/state/statusupdater_test.go
Labels: lgtm, approved, ok-to-test

#140 Sharpen the dependency on NFD in README.md.
  README.md
Labels: lgtm, approved

#143 MGMT-9686: update package runtime for openshift downstream
  pkg/runtime/runtime.go
  pkg/runtime/runtime_test.go
Labels: lgtm, approved

#146 Bug 2066359: SRO appends "arm64" instead of "aarch64" to the kernel name and it doesn't match the DTK
  pkg/upgrade/upgrade.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-urgent, backport-risk-assessed

#122 Bug 2060007: Makefile fixes for: no rule 'docker-push'
  Makefile
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-high, ok-to-test, backport-risk-assessed

#145 MGMT-9690: add OS configuration extraction from release image
  pkg/registry/mock_registry_api.go
  pkg/registry/registry.go
  pkg/runtime/mock_runtime_api.go
Labels: lgtm, approved

#147 MGMT-9705: add cluster pkg API for preflight support
  pkg/cluster/cluster.go
  pkg/cluster/cluster_test.go
  pkg/cluster/mock_cluster_api.go
Labels: lgtm, approved

#148 Set CONTAINER_COMMAND to podman by default
  Makefile.helper.mk
Labels: lgtm, approved

#150 MGMT-9766: change Makefile manager target output
  Makefile
Labels: lgtm, approved

#154 MGMT-9792: add an OC executable to the skipper container
  Dockerfile.special-resource-operator-build
Labels: lgtm, approved

#124 Use helm libraries as client only
  main.go
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
Labels: lgtm, approved

#155 MGMT-9798: Add makefile target for local test ConfigMap deployment
  Makefile
Labels: lgtm, approved

#156 MGMT-9731: add helmer package API for preflight preprocessing
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
Labels: lgtm, approved

#157 Adding a doc section on how to write good commit messages.
  CONTRIBUTING.md
Labels: lgtm, approved

#158 MGMT-9763: add resource pkg API to support preflight validations
  controllers/resources.go
  controllers/specialresource.go
  controllers/specialresource_controller.go
  main.go
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
  pkg/resource/mock_resource_api.go
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: lgtm, approved
