Repository openshift/special-resource-operator, pull requests merged in 2022-05, with the labels that each got.

#177 Enhancing returned errors for pkg/lifecycle.
  pkg/lifecycle/lifecycle.go
  pkg/utils/logging.go
Labels: lgtm, approved

#176 Bug 2079869: Builds for multiple kernel versions should be ran in parallel when possible
  controllers/specialresourcemodule_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#180 MGMT-10130: Enhance logging for preflight controller
  controllers/preflightvalidation_controller.go
Labels: lgtm, approved

#179 MGMT-10120: enhance logging for package preflight
  pkg/preflight/preflight.go
Labels: lgtm, approved

#181 Enhancing returned errors for pkg/runtime.
  pkg/runtime/runtime.go
Labels: lgtm, approved

#182 Enhancing returned errors for pkg/resource.
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: lgtm, approved

#184 Bug 2081081: fix the logging arguments error
  controllers/preflightvalidation_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#178 MGMT-10184: Remove special-resource-lifecycle configmap usage
  manifests/0014_configmap_special-resource-lifecycle.yaml
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/lifecycle/lifecycle.go
  pkg/lifecycle/lifecycle_test.go
  pkg/lifecycle/mock_lifecycle_api.go
  pkg/poll/poll.go
  pkg/poll/poll_test.go
Labels: lgtm, approved

#186 MGMT-10211: Remove platform-dependent code from controllers for downs…
  controllers/specialresource_controller.go
  controllers/specialresourcemodule_controller.go
  pkg/clients/clients.go
  pkg/clients/mock_clients_api.go
Labels: lgtm, approved

#187 MGMT-10113: enhance logging for clients package
  pkg/clients/clients.go
Labels: lgtm, approved

#191 MGMT-10119: Enhance logging for package poll
  pkg/poll/poll.go
Labels: lgtm, approved

#185 MGMT-10122: Enhance logging for package registry
  pkg/registry/registry.go
Labels: lgtm, approved

#188 Enhancing returned errors for specialresourcemodule controller.
  controllers/specialresourcemodule_controller.go
Labels: lgtm, approved

#200 MGMT-10287: add more logs to the resource package
  pkg/resource/resource.go
  pkg/resource/resource_test.go
Labels: lgtm, approved

#202 MGMT-10129: Enhance logging for package yamutils
  pkg/yamlutil/scan.go
Labels: lgtm, approved

#195 MGMT-10121: Enhance logging for package proxy
  pkg/proxy/proxy.go
Labels: lgtm, approved

#194 Bug 2070172: Use the SpecialResource's name as Helm release
  pkg/helmer/helmer.go
  pkg/helmer/helmer_test.go
  pkg/helmer/mock_helmer_api.go
  pkg/preflight/preflight.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#197 MGMT-10125: Enhance logging for package storage
  pkg/storage/storage.go
Labels: lgtm, approved

#201 MGMT-10127: Enhance logging for package utils
  pkg/utils/hash.go
  pkg/utils/osversion.go
Labels: lgtm, approved

#204 MGMT-10115: Enhance logging for package filter
  pkg/filter/filter.go
Labels: lgtm, approved

#196 MGMT-10276: add dependency on go vet command to the manager command
  Makefile
Labels: lgtm, approved

#207 MGMT-10259: Add info logs for specialresourcemodule controller
  controllers/specialresourcemodule_controller.go
Labels: lgtm, approved

#206 MGMT-10128: Enhance logging for package watcher
  pkg/watcher/watcher.go
Labels: lgtm, approved

#205 Enhancing returned errors for specialresource controller.
  controllers/specialresource.go
  controllers/specialresource_controller.go
Labels: lgtm, approved

#208 Bug 2084732: fix SRO CR finalization in case of an upgrade
  controllers/specialresource.go
  internal/controllers/finalizers/specialresource.go
  internal/controllers/finalizers/specialresource_test.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#210 Bug 2087993: removing unneeded log for preflight checks
  controllers/specialresource_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-urgent

#213 Bug 2083486: Support for operator Force/Managed/Removed/Unmanaged states
  api/v1beta1/specialresource_types.go
  config/crd/bases/sro.openshift.io_specialresources.yaml
  controllers/specialresource.go
  pkg/filter/filter.go
Labels: lgtm, approved, bugzilla/valid-bug, cherry-pick-approved, bugzilla/severity-medium, backport-risk-assessed

#214 Bug 2081821: Fixing a typo in the bundle string substitution for ART.
  bundle/art.yaml
  bundle/openshift-special-resource-operator.package.yaml
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#217 Bug 2089344: fix the Reconcilition function logs
  controllers/specialresource.go
  controllers/specialresource_controller.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium
