Repository openshift/special-resource-operator, pull requests merged in 2022-01, with the labels that each got.

#90 Bug 2034766: Fix hash annotation equal when updating recipe resources
  pkg/resource/resource.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-high

#92 Bug 2031875: Improve documentation for the SpecialResource API
  api/v1beta1/specialresource_types.go
  config/crd/bases/sro.openshift.io_specialresources.yaml
  manifests-k8s/0001_customresourcedefinition_specialresources.sro.openshift.io.yaml
  manifests/0001_customresourcedefinition_specialresources.sro.openshift.io.yaml
  pkg/helmer/api/v1beta1/helmer_types.go
Labels: lgtm, approved, bugzilla/valid-bug, bugzilla/severity-medium

#96 Fix poll pkg bug for buildconfig resources
  pkg/poll/poll.go
Labels: lgtm, approved

#94 Remove GitHub Actions
  .github/workflows/e2e.yaml
  .github/workflows/go-lint.yaml
  .github/workflows/helm-lint.yaml
  .github/workflows/image-master.yaml
  .github/workflows/image-remove.yaml
  .github/workflows/k8s-e2e.yaml
  .github/workflows/kube-lint.yaml
  .github/workflows/remove-label.yaml
  .github/workflows/unit.yaml
  .github/workflows/verify.yaml
Labels: lgtm, approved
